# This is a basic workflow to help you get started with Actions

name: Auto Update

# Controls when the action will run. 
on:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          submodules: recursive
          ref: release
          fetch-depth: 0
          
      - name: Pull data
        run: |
          git submodule update --init --recursive
          cd p5e-data
          git config user.email "action@github.com"
          git config user.name "Github Action"
          git fetch --all
          git reset --hard origin/no-variants
          
        
      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      # this Action should follow steps to set up Python build environment
      - name: Install Python dependencies
        uses: py-actions/py-dependency-install@v2
        with:
          path: "requirements.txt"
        
      - name: Build data
        run: python '${{ github.workspace }}/tools/workflow-make.py' 
      
      - name: Get version number
        run: |
          VER=$(cat VERSION)
          echo "VERSION=$VER" >> $GITHUB_ENV
          
      # Add and commit changes
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: 'Update ${{ env.VERSION }}'
      
      - uses: actions/upload-artifact@v2
        with:
          name: "v${{ env.VERSION }}"
          path: "${{ github.workspace }}/dist/Pokemon5e.zip"
